// builds/vue-quasar/src/components/RecordModal.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { PRIORITIES, STATUSES, SUBJECT_MAX, type Priority, type Status, type Ticket } from '@bakeoff/fixture';
import { formatDate, formatRelative } from '../format.js';
import { useToasts } from '../toasts.js';

/**
 * Section 6. Quasar's `QDialog` gives the `role="dialog"`, `aria-modal`, the
 * focus trap, initial focus, and focus-return to whatever had focus before the
 * dialog opened. Validation, touched tracking, and the unsaved-changes
 * confirmation are hand built on top, same as every other build in this
 * comparison since none of the eight libraries ship that as a primitive.
 */
const props = defineProps<{ ticket: Ticket | null; assignees: readonly string[] }>();
const emit = defineEmits<{ close: []; save: [updated: Ticket] }>();

const toasts = useToasts();

const subject = ref('');
const status = ref<Status>('open');
const priority = ref<Priority>('normal');
const assignee = ref<string | null>(null);
const touched = ref(false);
const subjectError = ref<string | null>(null);
const confirmOpen = ref(false);

watch(
  () => props.ticket,
  (ticket) => {
    if (!ticket) return;
    subject.value = ticket.subject;
    status.value = ticket.status;
    priority.value = ticket.priority;
    assignee.value = ticket.assignee;
    touched.value = false;
    subjectError.value = null;
    confirmOpen.value = false;
  },
  { immediate: true },
);

function onSubjectChange(value: string | number | null) {
  subject.value = value === null ? '' : String(value);
  touched.value = true;
  subjectError.value = null;
}

function onStatusChange(value: Status) {
  status.value = value;
  touched.value = true;
}

function onPriorityChange(value: Priority) {
  priority.value = value;
  touched.value = true;
}

function onAssigneeChange(value: string | null) {
  assignee.value = value;
  touched.value = true;
}

function requestClose() {
  if (touched.value) {
    confirmOpen.value = true;
    return;
  }
  emit('close');
}

function discard() {
  confirmOpen.value = false;
  emit('close');
}

function save() {
  if (!props.ticket) return;
  const length = subject.value.length;
  if (length === 0) {
    subjectError.value = 'Subject is required.';
    return;
  }
  if (length > SUBJECT_MAX) {
    subjectError.value = `Subject must be ${SUBJECT_MAX} characters or fewer.`;
    return;
  }
  const updated: Ticket = {
    ...props.ticket,
    subject: subject.value,
    status: status.value,
    priority: priority.value,
    assignee: assignee.value,
  };
  emit('save', updated);
  toasts.push(`Ticket ${props.ticket.id} updated`, 4000);
  emit('close');
}
</script>

<template>
  <q-dialog :model-value="ticket !== null" persistent>
    <q-card v-if="ticket" data-testid="record-dialog" style="min-width: 24rem" @keydown.esc="requestClose">
      <q-card-section>
        <div class="text-h6" data-testid="record-dialog-title">{{ ticket.id }}: {{ ticket.subject }}</div>
      </q-card-section>

      <q-card-section>
        <div class="field read-only-field">
          <span class="field-label">ID</span>
          <span>{{ ticket.id }}</span>
        </div>

        <div class="field">
          <q-input
            data-testid="modal-subject"
            label="Subject"
            :model-value="subject"
            :error="subjectError !== null"
            :error-message="subjectError ?? undefined"
            autofocus
            @update:model-value="onSubjectChange"
          />
        </div>

        <div class="field">
          <q-select
            data-testid="modal-status"
            label="Status"
            :options="[...STATUSES]"
            :model-value="status"
            emit-value
            map-options
            @update:model-value="onStatusChange"
          />
        </div>

        <div class="field">
          <q-select
            data-testid="modal-priority"
            label="Priority"
            :options="[...PRIORITIES]"
            :model-value="priority"
            emit-value
            map-options
            @update:model-value="onPriorityChange"
          />
        </div>

        <div class="field">
          <q-select
            data-testid="modal-assignee"
            label="Assignee"
            :options="[...assignees, 'Unassigned']"
            :model-value="assignee ?? 'Unassigned'"
            emit-value
            map-options
            @update:model-value="(v) => onAssigneeChange(v === 'Unassigned' ? null : (v as string))"
          />
        </div>

        <div class="field read-only-field">
          <span class="field-label">Created</span>
          <span>{{ formatDate(ticket.createdAt) }}</span>
        </div>
        <div class="field read-only-field">
          <span class="field-label">Updated</span>
          <span>{{ formatRelative(ticket.updatedAt) }}</span>
        </div>
      </q-card-section>

      <q-card-actions align="right">
        <q-btn label="Save" data-testid="modal-save" @click="save" />
        <q-btn label="Cancel" data-testid="modal-cancel" @click="requestClose" />
      </q-card-actions>
    </q-card>
  </q-dialog>

  <q-dialog :model-value="confirmOpen" persistent role="alertdialog">
    <q-card data-testid="confirm-dialog" @keydown.esc="confirmOpen = false">
      <q-card-section>
        <div class="text-h6">Discard unsaved changes?</div>
      </q-card-section>
      <q-card-section>
        <p>Closing now loses the edits made to this ticket.</p>
      </q-card-section>
      <q-card-actions align="right">
        <q-btn label="Discard changes" data-testid="confirm-discard" @click="discard" />
        <q-btn label="Keep editing" data-testid="confirm-keep" @click="confirmOpen = false" />
      </q-card-actions>
    </q-card>
  </q-dialog>
</template>

// builds/react-mui/src/components/RecordModal.tsx
import { useEffect, useState } from 'react';
import {
  Box,
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  TextField,
  Typography,
  type SelectChangeEvent,
} from '@mui/material';
import { PRIORITIES, STATUSES, SUBJECT_MAX, type Priority, type Status, type Ticket } from '@bakeoff/fixture';
import { useToasts } from '../toasts/ToastContext.js';
import { formatDate, formatRelative } from '../format.js';

const UNASSIGNED = 'Unassigned';

/**
 * Section 6. Material UI's `Dialog` gives `role="dialog"`, `aria-modal="true"`,
 * a real focus trap, and focus return to whatever had focus before the dialog
 * opened, all through its underlying `Modal`. `aria-labelledby` is wired
 * explicitly to the title's id rather than relied on implicitly. Validation,
 * the touched tracking, and the unsaved-changes confirmation are hand built.
 */
export function RecordModal({
  ticket,
  assignees,
  onClose,
  onSave,
}: {
  ticket: Ticket | null;
  assignees: readonly string[];
  onClose: () => void;
  onSave: (updated: Ticket) => void;
}) {
  const [subject, setSubject] = useState('');
  const [status, setStatus] = useState<Status>('open');
  const [priority, setPriority] = useState<Priority>('normal');
  const [assignee, setAssignee] = useState<string | null>(null);
  const [touched, setTouched] = useState(false);
  const [subjectError, setSubjectError] = useState<string | null>(null);
  const [confirmOpen, setConfirmOpen] = useState(false);
  const toasts = useToasts();

  useEffect(() => {
    if (!ticket) return;
    setSubject(ticket.subject);
    setStatus(ticket.status);
    setPriority(ticket.priority);
    setAssignee(ticket.assignee);
    setTouched(false);
    setSubjectError(null);
    setConfirmOpen(false);
  }, [ticket]);

  if (!ticket) return null;

  const requestClose = () => {
    if (touched) {
      setConfirmOpen(true);
      return;
    }
    onClose();
  };

  const discard = () => {
    setConfirmOpen(false);
    onClose();
  };

  const save = () => {
    const length = subject.length;
    if (length === 0) {
      setSubjectError('Subject is required.');
      return;
    }
    if (length > SUBJECT_MAX) {
      setSubjectError(`Subject must be ${SUBJECT_MAX} characters or fewer.`);
      return;
    }
    onSave({ ...ticket, subject, status, priority, assignee });
    toasts.push(`Ticket ${ticket.id} updated`, 4000);
    onClose();
  };

  return (
    <>
      <Dialog
        open
        onClose={requestClose}
        aria-labelledby="record-dialog-title"
        data-testid="record-dialog"
        fullWidth
        maxWidth="sm"
      >
        <DialogTitle id="record-dialog-title">
          {ticket.id}: {ticket.subject}
        </DialogTitle>
        <DialogContent className="record-dialog-content">
          <Box className="field read-only-field">
            <span className="field-label">ID</span>
            <span>{ticket.id}</span>
          </Box>

          <TextField
            id="ticket-subject"
            label="Subject"
            autoFocus
            fullWidth
            margin="dense"
            value={subject}
            error={subjectError !== null}
            helperText={subjectError}
            onChange={(event) => {
              setSubject(event.target.value);
              setTouched(true);
              setSubjectError(null);
            }}
          />

          <FormControl fullWidth margin="dense" data-testid="modal-status-field">
            <InputLabel id="modal-status-label">Status</InputLabel>
            <Select
              labelId="modal-status-label"
              label="Status"
              value={status}
              onChange={(event: SelectChangeEvent<Status>) => {
                setStatus(event.target.value as Status);
                setTouched(true);
              }}
            >
              {STATUSES.map((option) => (
                <MenuItem key={option} value={option} data-testid={`modal-status-option-${option}`}>
                  {option}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          <FormControl fullWidth margin="dense" data-testid="modal-priority-field">
            <InputLabel id="modal-priority-label">Priority</InputLabel>
            <Select
              labelId="modal-priority-label"
              label="Priority"
              value={priority}
              onChange={(event: SelectChangeEvent<Priority>) => {
                setPriority(event.target.value as Priority);
                setTouched(true);
              }}
            >
              {PRIORITIES.map((option) => (
                <MenuItem key={option} value={option} data-testid={`modal-priority-option-${option}`}>
                  {option}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          <FormControl fullWidth margin="dense" data-testid="modal-assignee-field">
            <InputLabel id="modal-assignee-label">Assignee</InputLabel>
            <Select
              labelId="modal-assignee-label"
              label="Assignee"
              value={assignee ?? UNASSIGNED}
              onChange={(event: SelectChangeEvent<string>) => {
                setAssignee(event.target.value === UNASSIGNED ? null : event.target.value);
                setTouched(true);
              }}
            >
              <MenuItem value={UNASSIGNED} data-testid="modal-assignee-option-Unassigned">
                {UNASSIGNED}
              </MenuItem>
              {assignees.map((name) => (
                <MenuItem key={name} value={name} data-testid={`modal-assignee-option-${name}`}>
                  {name}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          <Box className="field read-only-field">
            <span className="field-label">Created</span>
            <span>{formatDate(ticket.createdAt)}</span>
          </Box>
          <Box className="field read-only-field">
            <span className="field-label">Updated</span>
            <span>{formatRelative(ticket.updatedAt)}</span>
          </Box>
        </DialogContent>
        <DialogActions>
          <Button type="button" onClick={save}>
            Save
          </Button>
          <Button type="button" onClick={requestClose}>
            Cancel
          </Button>
        </DialogActions>
      </Dialog>

      <Dialog
        open={confirmOpen}
        onClose={() => setConfirmOpen(false)}
        aria-labelledby="confirm-dialog-title"
        data-testid="confirm-dialog"
        PaperProps={{ role: 'alertdialog' }}
      >
        <DialogTitle id="confirm-dialog-title">Discard unsaved changes?</DialogTitle>
        <DialogContent>
          <Typography>Closing now loses the edits made to this ticket.</Typography>
        </DialogContent>
        <DialogActions>
          <Button type="button" onClick={discard}>
            Discard changes
          </Button>
          <Button type="button" onClick={() => setConfirmOpen(false)}>
            Keep editing
          </Button>
        </DialogActions>
      </Dialog>
    </>
  );
}
