// builds/vue-quasar/src/components/RecordModal.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { PRIORITIES, STATUSES, SUBJECT_MAX, type Priority, type Status, type Ticket } from '@bakeoff/fixture';
import { formatDate, formatRelative } from '../format.js';
import { useToasts } from '../toasts.js';

/**
 * Section 6. Quasar's `QDialog` gives the `role="dialog"`, `aria-modal`, the
 * focus trap, initial focus, and focus-return to whatever had focus before the
 * dialog opened. Validation, touched tracking, and the unsaved-changes
 * confirmation are hand built on top, same as every other build in this
 * comparison since none of the eight libraries ship that as a primitive.
 */
const props = defineProps<{ ticket: Ticket | null; assignees: readonly string[] }>();
const emit = defineEmits<{ close: []; save: [updated: Ticket] }>();

const toasts = useToasts();

const subject = ref('');
const status = ref<Status>('open');
const priority = ref<Priority>('normal');
const assignee = ref<string | null>(null);
const touched = ref(false);
const subjectError = ref<string | null>(null);
const confirmOpen = ref(false);

watch(
  () => props.ticket,
  (ticket) => {
    if (!ticket) return;
    subject.value = ticket.subject;
    status.value = ticket.status;
    priority.value = ticket.priority;
    assignee.value = ticket.assignee;
    touched.value = false;
    subjectError.value = null;
    confirmOpen.value = false;
  },
  { immediate: true },
);

function onSubjectChange(value: string | number | null) {
  subject.value = value === null ? '' : String(value);
  touched.value = true;
  subjectError.value = null;
}

function onStatusChange(value: Status) {
  status.value = value;
  touched.value = true;
}

function onPriorityChange(value: Priority) {
  priority.value = value;
  touched.value = true;
}

function onAssigneeChange(value: string | null) {
  assignee.value = value;
  touched.value = true;
}

function requestClose() {
  if (touched.value) {
    confirmOpen.value = true;
    return;
  }
  emit('close');
}

function discard() {
  confirmOpen.value = false;
  emit('close');
}

function save() {
  if (!props.ticket) return;
  const length = subject.value.length;
  if (length === 0) {
    subjectError.value = 'Subject is required.';
    return;
  }
  if (length > SUBJECT_MAX) {
    subjectError.value = `Subject must be ${SUBJECT_MAX} characters or fewer.`;
    return;
  }
  const updated: Ticket = {
    ...props.ticket,
    subject: subject.value,
    status: status.value,
    priority: priority.value,
    assignee: assignee.value,
  };
  emit('save', updated);
  toasts.push(`Ticket ${props.ticket.id} updated`, 4000);
  emit('close');
}
</script>

<template>
  <q-dialog :model-value="ticket !== null" persistent>
    <q-card v-if="ticket" data-testid="record-dialog" style="min-width: 24rem" @keydown.esc="requestClose">
      <q-card-section>
        <div class="text-h6" data-testid="record-dialog-title">{{ ticket.id }}: {{ ticket.subject }}</div>
      </q-card-section>

      <q-card-section>
        <div class="field read-only-field">
          <span class="field-label">ID</span>
          <span>{{ ticket.id }}</span>
        </div>

        <div class="field">
          <q-input
            data-testid="modal-subject"
            label="Subject"
            :model-value="subject"
            :error="subjectError !== null"
            :error-message="subjectError ?? undefined"
            autofocus
            @update:model-value="onSubjectChange"
          />
        </div>

        <div class="field">
          <q-select
            data-testid="modal-status"
            label="Status"
            :options="[...STATUSES]"
            :model-value="status"
            emit-value
            map-options
            @update:model-value="onStatusChange"
          />
        </div>

        <div class="field">
          <q-select
            data-testid="modal-priority"
            label="Priority"
            :options="[...PRIORITIES]"
            :model-value="priority"
            emit-value
            map-options
            @update:model-value="onPriorityChange"
          />
        </div>

        <div class="field">
          <q-select
            data-testid="modal-assignee"
            label="Assignee"
            :options="[...assignees, 'Unassigned']"
            :model-value="assignee ?? 'Unassigned'"
            emit-value
            map-options
            @update:model-value="(v) => onAssigneeChange(v === 'Unassigned' ? null : (v as string))"
          />
        </div>

        <div class="field read-only-field">
          <span class="field-label">Created</span>
          <span>{{ formatDate(ticket.createdAt) }}</span>
        </div>
        <div class="field read-only-field">
          <span class="field-label">Updated</span>
          <span>{{ formatRelative(ticket.updatedAt) }}</span>
        </div>
      </q-card-section>

      <q-card-actions align="right">
        <q-btn label="Save" data-testid="modal-save" @click="save" />
        <q-btn label="Cancel" data-testid="modal-cancel" @click="requestClose" />
      </q-card-actions>
    </q-card>
  </q-dialog>

  <q-dialog :model-value="confirmOpen" persistent role="alertdialog">
    <q-card data-testid="confirm-dialog" @keydown.esc="confirmOpen = false">
      <q-card-section>
        <div class="text-h6">Discard unsaved changes?</div>
      </q-card-section>
      <q-card-section>
        <p>Closing now loses the edits made to this ticket.</p>
      </q-card-section>
      <q-card-actions align="right">
        <q-btn label="Discard changes" data-testid="confirm-discard" @click="discard" />
        <q-btn label="Keep editing" data-testid="confirm-keep" @click="confirmOpen = false" />
      </q-card-actions>
    </q-card>
  </q-dialog>
</template>

// builds/react-chakra/src/components/RecordModal.tsx
import { useEffect, useState } from 'react';
import type { ChangeEvent } from 'react';
import { Button, Dialog, Field, HStack, Input, NativeSelect, Stack, Text } from '@chakra-ui/react';
import { PRIORITIES, STATUSES, SUBJECT_MAX, type Priority, type Status, type Ticket } from '@bakeoff/fixture';
import { formatDate, formatRelative } from '../format.js';
import { pushToast } from '../toasts.js';

const UNASSIGNED = 'Unassigned';

/**
 * Section 6. Chakra's `Dialog` (Ark UI underneath) supplies `role="dialog"`,
 * `aria-modal="true"`, the title association, the focus trap, and focus
 * return to the row that opened it. Validation, the touched tracking, and the
 * unsaved-changes confirmation are hand built on top, the same as they would
 * be for any dialog primitive: section 6's rules are specific to this screen,
 * not something a generic dialog ships.
 */
export function RecordModal({
  ticket,
  assignees,
  onClose,
  onSave,
}: {
  ticket: Ticket | null;
  assignees: readonly string[];
  onClose: () => void;
  onSave: (updated: Ticket) => void;
}) {
  const [subject, setSubject] = useState('');
  const [status, setStatus] = useState<Status>('open');
  const [priority, setPriority] = useState<Priority>('normal');
  const [assignee, setAssignee] = useState<string | null>(null);
  const [touched, setTouched] = useState(false);
  const [subjectError, setSubjectError] = useState<string | null>(null);
  const [confirmOpen, setConfirmOpen] = useState(false);

  useEffect(() => {
    if (!ticket) return;
    setSubject(ticket.subject);
    setStatus(ticket.status);
    setPriority(ticket.priority);
    setAssignee(ticket.assignee);
    setTouched(false);
    setSubjectError(null);
    setConfirmOpen(false);
  }, [ticket]);

  if (!ticket) return null;

  const requestClose = () => {
    if (touched) {
      setConfirmOpen(true);
      return;
    }
    onClose();
  };

  const discard = () => {
    setConfirmOpen(false);
    onClose();
  };

  const save = () => {
    const length = subject.length;
    if (length === 0) {
      setSubjectError('Subject is required.');
      return;
    }
    if (length > SUBJECT_MAX) {
      setSubjectError(`Subject must be ${SUBJECT_MAX} characters or fewer.`);
      return;
    }
    onSave({ ...ticket, subject, status, priority, assignee });
    pushToast(`Ticket ${ticket.id} updated`, 4000);
    onClose();
  };

  const onSubjectChange = (event: ChangeEvent<HTMLInputElement>) => {
    setSubject(event.target.value);
    setTouched(true);
    setSubjectError(null);
  };

  const onStatusChange = (event: ChangeEvent<HTMLSelectElement>) => {
    setStatus(event.target.value as Status);
    setTouched(true);
  };

  const onPriorityChange = (event: ChangeEvent<HTMLSelectElement>) => {
    setPriority(event.target.value as Priority);
    setTouched(true);
  };

  const onAssigneeChange = (event: ChangeEvent<HTMLSelectElement>) => {
    setAssignee(event.target.value === '' ? null : event.target.value);
    setTouched(true);
  };

  return (
    <>
      <Dialog.Root
        open
        role="dialog"
        onOpenChange={(details) => {
          if (!details.open) requestClose();
        }}
      >
        <Dialog.Backdrop />
        <Dialog.Positioner>
          <Dialog.Content data-testid="record-dialog" maxW="30rem">
            <Dialog.Header>
              <Dialog.Title>
                {ticket.id}: {ticket.subject}
              </Dialog.Title>
            </Dialog.Header>
            <Dialog.Body>
              <Stack gap="4">
                <HStack justify="space-between">
                  <Text fontWeight="semibold">ID</Text>
                  <Text>{ticket.id}</Text>
                </HStack>

                <Field.Root invalid={!!subjectError}>
                  <Field.Label htmlFor="ticket-subject">Subject</Field.Label>
                  <Input
                    id="ticket-subject"
                    value={subject}
                    aria-invalid={subjectError ? true : undefined}
                    aria-describedby={subjectError ? 'ticket-subject-error' : undefined}
                    onChange={onSubjectChange}
                  />
                  <Field.ErrorText id="ticket-subject-error">{subjectError}</Field.ErrorText>
                </Field.Root>

                <Field.Root>
                  <Field.Label htmlFor="modal-status">Status</Field.Label>
                  <NativeSelect.Root>
                    <NativeSelect.Field
                      id="modal-status"
                      data-testid="modal-status"
                      value={status}
                      onChange={onStatusChange}
                    >
                      {STATUSES.map((s) => (
                        <option key={s} value={s}>
                          {s}
                        </option>
                      ))}
                    </NativeSelect.Field>
                    <NativeSelect.Indicator />
                  </NativeSelect.Root>
                </Field.Root>

                <Field.Root>
                  <Field.Label htmlFor="modal-priority">Priority</Field.Label>
                  <NativeSelect.Root>
                    <NativeSelect.Field
                      id="modal-priority"
                      data-testid="modal-priority"
                      value={priority}
                      onChange={onPriorityChange}
                    >
                      {PRIORITIES.map((p) => (
                        <option key={p} value={p}>
                          {p}
                        </option>
                      ))}
                    </NativeSelect.Field>
                    <NativeSelect.Indicator />
                  </NativeSelect.Root>
                </Field.Root>

                <Field.Root>
                  <Field.Label htmlFor="modal-assignee">Assignee</Field.Label>
                  <NativeSelect.Root>
                    <NativeSelect.Field
                      id="modal-assignee"
                      data-testid="modal-assignee"
                      value={assignee ?? UNASSIGNED}
                      onChange={onAssigneeChange}
                    >
                      {assignees.map((name) => (
                        <option key={name} value={name}>
                          {name}
                        </option>
                      ))}
                      <option value={UNASSIGNED}>{UNASSIGNED}</option>
                    </NativeSelect.Field>
                    <NativeSelect.Indicator />
                  </NativeSelect.Root>
                </Field.Root>

                <HStack justify="space-between">
                  <Text fontWeight="semibold">Created</Text>
                  <Text>{formatDate(ticket.createdAt)}</Text>
                </HStack>
                <HStack justify="space-between">
                  <Text fontWeight="semibold">Updated</Text>
                  <Text>{formatRelative(ticket.updatedAt)}</Text>
                </HStack>
              </Stack>
            </Dialog.Body>
            <Dialog.Footer>
              <Button type="button" onClick={requestClose} variant="outline">
                Cancel
              </Button>
              <Button type="button" onClick={save}>
                Save
              </Button>
            </Dialog.Footer>
          </Dialog.Content>
        </Dialog.Positioner>
      </Dialog.Root>

      <Dialog.Root
        open={confirmOpen}
        role="alertdialog"
        onOpenChange={(details) => {
          if (!details.open) setConfirmOpen(false);
        }}
      >
        <Dialog.Backdrop />
        <Dialog.Positioner>
          <Dialog.Content data-testid="confirm-dialog" maxW="24rem">
            <Dialog.Header>
              <Dialog.Title>Discard unsaved changes?</Dialog.Title>
            </Dialog.Header>
            <Dialog.Body>
              <Text>Closing now loses the edits made to this ticket.</Text>
            </Dialog.Body>
            <Dialog.Footer>
              <Button type="button" variant="outline" onClick={() => setConfirmOpen(false)}>
                Keep editing
              </Button>
              <Button type="button" onClick={discard}>
                Discard changes
              </Button>
            </Dialog.Footer>
          </Dialog.Content>
        </Dialog.Positioner>
      </Dialog.Root>
    </>
  );
}
