// builds/react-chakra/src/components/Badge.tsx
import { Badge as ChakraBadge } from '@chakra-ui/react';
import type { Priority, Status } from '@bakeoff/fixture';

const STATUS_PALETTE: Record<Status, string> = {
  open: 'blue',
  pending: 'yellow',
  resolved: 'green',
  closed: 'gray',
};

const PRIORITY_PALETTE: Record<Priority, string> = {
  low: 'gray',
  normal: 'blue',
  high: 'orange',
  urgent: 'red',
};

/** Section 3: status and priority render as badges, using Chakra's `Badge`. */
export function Badge({ kind, value }: { kind: 'status' | 'priority'; value: Status | Priority }) {
  const palette = kind === 'status' ? STATUS_PALETTE[value as Status] : PRIORITY_PALETTE[value as Priority];
  return (
    <ChakraBadge colorPalette={palette} textTransform="capitalize" data-testid={`badge-${kind}`}>
      {value}
    </ChakraBadge>
  );
}

// builds/vue-vuetify/src/components/Badge.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { Priority, Status } from '@bakeoff/fixture';

/** Section 3: status and priority render as badges, built on Vuetify's `v-chip`. */
const props = defineProps<{ kind: 'status' | 'priority'; value: Status | Priority }>();

const STATUS_COLOR: Record<Status, string> = {
  open: 'primary',
  pending: 'warning',
  resolved: 'success',
  closed: 'surface-variant',
};

const PRIORITY_COLOR: Record<Priority, string> = {
  low: 'surface-variant',
  normal: 'primary',
  high: 'warning',
  urgent: 'error',
};

const color = computed(() =>
  props.kind === 'status' ? STATUS_COLOR[props.value as Status] : PRIORITY_COLOR[props.value as Priority],
);
</script>

<template>
  <v-chip :class="`badge badge-${kind}-${value}`" size="small" :color="color" label>{{ value }}</v-chip>
</template>
