// builds/react-mui/src/components/Badge.tsx
import { Chip } from '@mui/material';
import type { Priority, Status } from '@uilc/fixture';

const STATUS_COLOR: Record<Status, 'info' | 'warning' | 'success' | 'default'> = {
  open: 'info',
  pending: 'warning',
  resolved: 'success',
  closed: 'default',
};

const PRIORITY_COLOR: Record<Priority, 'default' | 'info' | 'warning' | 'error'> = {
  low: 'default',
  normal: 'info',
  high: 'warning',
  urgent: 'error',
};

/** Section 3: status and priority render as badges. Material UI's `Chip` covers this directly. */
export function Badge({ kind, value }: { kind: 'status' | 'priority'; value: Status | Priority }) {
  const color = kind === 'status' ? STATUS_COLOR[value as Status] : PRIORITY_COLOR[value as Priority];
  return <Chip size="small" label={value} color={color} variant="outlined" />;
}

// builds/vue-vuetify/src/components/Badge.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { Priority, Status } from '@uilc/fixture';

/** Section 3: status and priority render as badges, built on Vuetify's `v-chip`. */
const props = defineProps<{ kind: 'status' | 'priority'; value: Status | Priority }>();

const STATUS_COLOR: Record<Status, string> = {
  open: 'primary',
  pending: 'warning',
  resolved: 'success',
  closed: 'surface-variant',
};

const PRIORITY_COLOR: Record<Priority, string> = {
  low: 'surface-variant',
  normal: 'primary',
  high: 'warning',
  urgent: 'error',
};

const color = computed(() =>
  props.kind === 'status' ? STATUS_COLOR[props.value as Status] : PRIORITY_COLOR[props.value as Priority],
);
</script>

<template>
  <v-chip :class="`badge badge-${kind}-${value}`" size="small" :color="color" label>{{ value }}</v-chip>
</template>
