// builds/react-chakra/src/components/TicketsTable.tsx
import type { KeyboardEvent } from 'react';
import { Box, Button, HStack, Table, Text, VisuallyHidden } from '@chakra-ui/react';
import { PAGE_SIZE, type Ticket } from '@bakeoff/fixture';
import { formatDate, formatRelative } from '../format.js';
import type { SortColumn, SortDirection } from '../filtering.js';
import { sortRows } from '../filtering.js';
import { Badge } from './Badge.js';
import { TableEmptyState, type TableEmptyKind } from './TableEmptyState.js';

export interface SortState {
  column: SortColumn | null;
  direction: SortDirection;
}

function ariaSortFor(sort: SortState, column: SortColumn): 'ascending' | 'descending' | undefined {
  if (sort.column !== column) return undefined;
  return sort.direction;
}

export function TicketsTable({
  filtered,
  page,
  onPageChange,
  sort,
  onSort,
  onOpenRow,
  emptyKind,
  emptyMessage,
  onClearFilters,
}: {
  filtered: Ticket[];
  page: number;
  onPageChange: (page: number) => void;
  sort: SortState;
  onSort: (column: SortColumn) => void;
  onOpenRow: (ticket: Ticket) => void;
  emptyKind: TableEmptyKind | null;
  emptyMessage: string | null;
  onClearFilters: () => void;
}) {
  const total = filtered.length;
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  const clampedPage = Math.min(Math.max(page, 1), totalPages);
  const sorted = sortRows(filtered, sort.column, sort.direction);
  const pageRows = sorted.slice((clampedPage - 1) * PAGE_SIZE, clampedPage * PAGE_SIZE);
  const start = total === 0 ? 0 : (clampedPage - 1) * PAGE_SIZE + 1;
  const end = Math.min(clampedPage * PAGE_SIZE, total);

  const onRowKeyDown = (ticket: Ticket) => (event: KeyboardEvent<HTMLTableRowElement>) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      onOpenRow(ticket);
    }
  };

  const headerButton = (key: SortColumn, label: string) => (
    <Table.ColumnHeader key={key} aria-sort={ariaSortFor(sort, key) ?? 'none'}>
      <Button variant="plain" size="sm" px="0" fontWeight="semibold" onClick={() => onSort(key)}>
        {label}
        {sort.column === key ? (sort.direction === 'ascending' ? ' ▲' : ' ▼') : ''}
      </Button>
    </Table.ColumnHeader>
  );

  return (
    <Box>
      <Table.ScrollArea>
        <Table.Root>
          <VisuallyHidden asChild>
            <caption>Support tickets</caption>
          </VisuallyHidden>
          <Table.Header>
            <Table.Row>
              {headerButton('id', 'ID')}
              {headerButton('subject', 'Subject')}
              <Table.ColumnHeader>Status</Table.ColumnHeader>
              <Table.ColumnHeader>Priority</Table.ColumnHeader>
              <Table.ColumnHeader>Assignee</Table.ColumnHeader>
              {headerButton('created', 'Created')}
              {headerButton('updated', 'Updated')}
            </Table.Row>
          </Table.Header>
          <Table.Body>
            {emptyKind ? (
              <Table.Row>
                <Table.Cell colSpan={7} p="0" border="none">
                  <TableEmptyState
                    kind={emptyKind}
                    message={emptyMessage ?? ''}
                    onAction={onClearFilters}
                  />
                </Table.Cell>
              </Table.Row>
            ) : (
              pageRows.map((ticket) => (
                <Table.Row
                  key={ticket.id}
                  data-testid="ticket-row"
                  tabIndex={0}
                  cursor="pointer"
                  onClick={() => onOpenRow(ticket)}
                  onKeyDown={onRowKeyDown(ticket)}
                >
                  <Table.Cell>{ticket.id}</Table.Cell>
                  <Table.Cell>{ticket.subject}</Table.Cell>
                  <Table.Cell>
                    <Badge kind="status" value={ticket.status} />
                  </Table.Cell>
                  <Table.Cell>
                    <Badge kind="priority" value={ticket.priority} />
                  </Table.Cell>
                  <Table.Cell>{ticket.assignee ?? 'Unassigned'}</Table.Cell>
                  <Table.Cell>{formatDate(ticket.createdAt)}</Table.Cell>
                  <Table.Cell>{formatRelative(ticket.updatedAt)}</Table.Cell>
                </Table.Row>
              ))
            )}
          </Table.Body>
        </Table.Root>
      </Table.ScrollArea>

      {emptyKind ? null : (
        <HStack mt="3" gap="3">
          <Text aria-live="polite">
            Showing {start} to {end} of {total}
          </Text>
          <Button size="sm" variant="outline" onClick={() => onPageChange(1)} disabled={clampedPage === 1}>
            First
          </Button>
          <Button size="sm" variant="outline" onClick={() => onPageChange(clampedPage - 1)} disabled={clampedPage === 1}>
            Previous
          </Button>
          <Button
            size="sm"
            variant="outline"
            onClick={() => onPageChange(clampedPage + 1)}
            disabled={clampedPage === totalPages}
          >
            Next
          </Button>
          <Button
            size="sm"
            variant="outline"
            onClick={() => onPageChange(totalPages)}
            disabled={clampedPage === totalPages}
          >
            Last
          </Button>
        </HStack>
      )}
    </Box>
  );
}

// builds/vue-vuetify/src/components/TicketsTable.vue
<script setup lang="ts">
import { computed } from 'vue';
import { PAGE_SIZE, type Ticket } from '@bakeoff/fixture';
import { formatDate, formatRelative } from '../format.js';
import { sortRows, type SortColumn, type SortDirection } from '../filtering.js';
import Badge from './Badge.vue';

export interface SortState {
  column: SortColumn | null;
  direction: SortDirection;
}

const props = defineProps<{
  filtered: Ticket[];
  page: number;
  sort: SortState;
  emptyKind: 'no-tickets' | 'no-matches' | null;
  emptyMessage: string | null;
}>();

const emit = defineEmits<{
  'page-change': [page: number];
  sort: [column: SortColumn];
  'open-row': [ticket: Ticket];
  'clear-filters': [];
}>();

const COLUMNS: { key: SortColumn; label: string }[] = [
  { key: 'id', label: 'ID' },
  { key: 'subject', label: 'Subject' },
  { key: 'created', label: 'Created' },
  { key: 'updated', label: 'Updated' },
];

function ariaSortFor(column: SortColumn): 'ascending' | 'descending' | 'none' {
  if (props.sort.column !== column) return 'none';
  return props.sort.direction;
}

const totalPages = computed(() => Math.max(1, Math.ceil(props.filtered.length / PAGE_SIZE)));
const clampedPage = computed(() => Math.min(Math.max(props.page, 1), totalPages.value));
const sorted = computed(() => sortRows(props.filtered, props.sort.column, props.sort.direction));
const pageRows = computed(() =>
  sorted.value.slice((clampedPage.value - 1) * PAGE_SIZE, clampedPage.value * PAGE_SIZE),
);
const total = computed(() => props.filtered.length);
const start = computed(() => (total.value === 0 ? 0 : (clampedPage.value - 1) * PAGE_SIZE + 1));
const end = computed(() => Math.min(clampedPage.value * PAGE_SIZE, total.value));

function onRowKeydown(ticket: Ticket, event: KeyboardEvent): void {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    emit('open-row', ticket);
  }
}
</script>

<template>
  <div class="table-region">
    <v-table>
      <caption class="visually-hidden">Support tickets</caption>
      <thead>
        <tr>
          <th
            v-for="col in COLUMNS.slice(0, 2)"
            :key="col.key"
            scope="col"
            :aria-sort="ariaSortFor(col.key)"
          >
            <v-btn :data-testid="`sort-${col.key}`" variant="text" density="compact" @click="emit('sort', col.key)">
              {{ col.label }}<span aria-hidden="true">{{ sort.column === col.key ? (sort.direction === 'ascending' ? ' ▲' : ' ▼') : '' }}</span>
            </v-btn>
          </th>
          <th scope="col">Status</th>
          <th scope="col">Priority</th>
          <th scope="col">Assignee</th>
          <th
            v-for="col in COLUMNS.slice(2)"
            :key="col.key"
            scope="col"
            :aria-sort="ariaSortFor(col.key)"
          >
            <v-btn :data-testid="`sort-${col.key}`" variant="text" density="compact" @click="emit('sort', col.key)">
              {{ col.label }}<span aria-hidden="true">{{ sort.column === col.key ? (sort.direction === 'ascending' ? ' ▲' : ' ▼') : '' }}</span>
            </v-btn>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-if="emptyKind">
          <td colspan="7" data-testid="table-empty-state" :data-kind="emptyKind">
            <p>{{ emptyMessage }}</p>
            <v-btn
              v-if="emptyKind === 'no-matches'"
              data-testid="empty-state-action"
              variant="tonal"
              @click="emit('clear-filters')"
            >
              Clear filters
            </v-btn>
          </td>
        </tr>
        <tr
          v-for="ticket in pageRows"
          v-else
          :key="ticket.id"
          data-testid="ticket-row"
          tabindex="0"
          @click="emit('open-row', ticket)"
          @keydown="onRowKeydown(ticket, $event)"
        >
          <td>{{ ticket.id }}</td>
          <td>{{ ticket.subject }}</td>
          <td><Badge kind="status" :value="ticket.status" /></td>
          <td><Badge kind="priority" :value="ticket.priority" /></td>
          <td>{{ ticket.assignee ?? 'Unassigned' }}</td>
          <td>{{ formatDate(ticket.createdAt) }}</td>
          <td>{{ formatRelative(ticket.updatedAt) }}</td>
        </tr>
      </tbody>
    </v-table>

    <div v-if="!emptyKind" class="pagination">
      <p aria-live="polite">Showing {{ start }} to {{ end }} of {{ total }}</p>
      <v-btn data-testid="page-first" variant="tonal" density="compact" :disabled="clampedPage === 1" @click="emit('page-change', 1)">First</v-btn>
      <v-btn data-testid="page-previous" variant="tonal" density="compact" :disabled="clampedPage === 1" @click="emit('page-change', clampedPage - 1)">Previous</v-btn>
      <v-btn data-testid="page-next" variant="tonal" density="compact" :disabled="clampedPage === totalPages" @click="emit('page-change', clampedPage + 1)">Next</v-btn>
      <v-btn data-testid="page-last" variant="tonal" density="compact" :disabled="clampedPage === totalPages" @click="emit('page-change', totalPages)">Last</v-btn>
    </div>
  </div>
</template>
