// builds/react-headless/src/components/Badge.tsx
import type { Priority, Status } from '@uilc/fixture';

/** Section 3: status and priority render as badges. Plain elements, no Headless UI component covers this. */
export function Badge({ kind, value }: { kind: 'status' | 'priority'; value: Status | Priority }) {
  return <span className={`badge badge-${kind}-${value}`}>{value}</span>;
}

// builds/vue-quasar/src/components/Badge.vue
<script setup lang="ts">
import type { Priority, Status } from '@uilc/fixture';

/** Section 3: status and priority render as badges via Quasar's QBadge. */
defineProps<{ kind: 'status' | 'priority'; value: Status | Priority }>();
</script>

<template>
  <q-badge :class="`badge-${kind}-${value}`" :label="value" />
</template>
