// builds/react-mui/src/components/FilterForm.tsx
import type { ChangeEvent } from 'react';
import {
  Box,
  Button,
  Checkbox,
  FormControl,
  InputLabel,
  ListItemText,
  MenuItem,
  Select,
  TextField,
  Typography,
  type SelectChangeEvent,
} from '@mui/material';
import { PRIORITIES, STATUSES, type Priority, type Status } from '@bakeoff/fixture';
import type { FiltersApi } from '../useFilters.js';

/**
 * Section 5. Filters on every keystroke or change, no submit button. Material
 * UI's `Select` (`multiple`) gives keyboard navigation, `aria-expanded`,
 * `role="listbox"`/`role="option"`, and the label association through
 * `InputLabel` + `labelId`; the field layout and the active-count summary
 * next to Clear are hand built.
 */
export function FilterForm({ filters, assignees }: { filters: FiltersApi; assignees: readonly string[] }) {
  const onSearchChange = (event: ChangeEvent<HTMLInputElement>) => filters.setSearch(event.target.value);
  const onFromChange = (event: ChangeEvent<HTMLInputElement>) =>
    filters.setCreatedFrom(event.target.value === '' ? null : event.target.value);
  const onToChange = (event: ChangeEvent<HTMLInputElement>) =>
    filters.setCreatedTo(event.target.value === '' ? null : event.target.value);

  const onStatusChange = (event: SelectChangeEvent<Status[]>) => {
    const value = event.target.value;
    filters.setStatus(typeof value === 'string' ? (value.split(',') as Status[]) : value);
  };

  const onPriorityChange = (event: SelectChangeEvent<Priority[]>) => {
    const value = event.target.value;
    filters.setPriority(typeof value === 'string' ? (value.split(',') as Priority[]) : value);
  };

  const onAssigneeChange = (event: SelectChangeEvent<string>) => {
    filters.setAssignee(event.target.value === '' ? null : event.target.value);
  };

  return (
    <Box
      component="form"
      className="filter-form"
      aria-label="Filter tickets"
      onSubmit={(e) => e.preventDefault()}
      data-testid="filter-form"
    >
      <TextField
        id="search-input"
        label="Search"
        value={filters.fields.search}
        onChange={onSearchChange}
        placeholder="Search id or subject"
        size="small"
      />

      <FormControl size="small" className="field" data-testid="filter-status-field">
        <InputLabel id="filter-status-label">Status</InputLabel>
        <Select
          labelId="filter-status-label"
          label="Status"
          multiple
          displayEmpty
          value={filters.fields.status}
          onChange={onStatusChange}
          renderValue={(selected) => (selected.length === 0 ? 'Any status' : selected.join(', '))}
        >
          {STATUSES.map((option) => (
            <MenuItem key={option} value={option} data-testid={`filter-status-option-${option}`}>
              <Checkbox size="small" checked={filters.fields.status.includes(option)} />
              <ListItemText primary={option} />
            </MenuItem>
          ))}
        </Select>
      </FormControl>

      <FormControl size="small" className="field" data-testid="filter-priority-field">
        <InputLabel id="filter-priority-label">Priority</InputLabel>
        <Select
          labelId="filter-priority-label"
          label="Priority"
          multiple
          displayEmpty
          value={filters.fields.priority}
          onChange={onPriorityChange}
          renderValue={(selected) => (selected.length === 0 ? 'Any priority' : selected.join(', '))}
        >
          {PRIORITIES.map((option) => (
            <MenuItem key={option} value={option} data-testid={`filter-priority-option-${option}`}>
              <Checkbox size="small" checked={filters.fields.priority.includes(option)} />
              <ListItemText primary={option} />
            </MenuItem>
          ))}
        </Select>
      </FormControl>

      <FormControl size="small" className="field" data-testid="filter-assignee-field">
        <InputLabel id="filter-assignee-label">Assignee</InputLabel>
        <Select
          labelId="filter-assignee-label"
          label="Assignee"
          displayEmpty
          value={filters.fields.assignee ?? ''}
          onChange={onAssigneeChange}
          renderValue={(selected) => (selected === '' ? 'Any assignee' : (selected as string))}
        >
          <MenuItem value="" data-testid="filter-assignee-option-null">
            Any assignee
          </MenuItem>
          {[...assignees, 'Unassigned'].map((name) => (
            <MenuItem key={name} value={name} data-testid={`filter-assignee-option-${name}`}>
              {name}
            </MenuItem>
          ))}
        </Select>
      </FormControl>

      <Box component="fieldset" className="field created-range">
        <legend>Created between</legend>
        <TextField
          id="created-from"
          label="From"
          type="date"
          size="small"
          slotProps={{ inputLabel: { shrink: true } }}
          value={filters.fields.createdFrom ?? ''}
          onChange={onFromChange}
        />
        <TextField
          id="created-to"
          label="To"
          type="date"
          size="small"
          slotProps={{ inputLabel: { shrink: true } }}
          value={filters.fields.createdTo ?? ''}
          onChange={onToChange}
        />
      </Box>

      <Box className="field clear-field">
        <Typography variant="body2" data-testid="filter-active-count">
          {filters.activeCount} active
        </Typography>
        <Button
          type="button"
          variant="outlined"
          size="small"
          data-testid="filter-clear-button"
          onClick={filters.clear}
          disabled={filters.activeCount === 0}
        >
          Clear filters
        </Button>
      </Box>
    </Box>
  );
}

// builds/vue-quasar/src/components/FilterForm.vue
<script setup lang="ts">
import { PRIORITIES, STATUSES, type Priority, type Status } from '@bakeoff/fixture';
import type { FiltersApi } from '../useFilters.js';

/** Section 5. Filters on every keystroke or change, no submit button. */
const props = defineProps<{ filters: FiltersApi; assignees: readonly string[] }>();

const ANY_ASSIGNEE = 'Any assignee';

const assigneeOptions = () => [ANY_ASSIGNEE, ...props.assignees, 'Unassigned'];

function onFromChange(value: string | number | null) {
  const text = value === null ? '' : String(value);
  props.filters.setCreatedFrom(text === '' ? null : text);
}

function onToChange(value: string | number | null) {
  const text = value === null ? '' : String(value);
  props.filters.setCreatedTo(text === '' ? null : text);
}

function onAssigneeChange(value: string) {
  props.filters.setAssignee(value === ANY_ASSIGNEE ? null : value);
}
</script>

<template>
  <form class="filter-form" aria-label="Filter tickets" @submit.prevent>
    <div class="field">
      <q-input
        data-testid="filter-search"
        label="Search"
        placeholder="Search id or subject"
        :model-value="filters.fields.search"
        @update:model-value="(v) => filters.setSearch(String(v ?? ''))"
      />
    </div>

    <div class="field">
      <q-select
        data-testid="filter-status"
        label="Status"
        :options="[...STATUSES]"
        :model-value="filters.fields.status"
        multiple
        emit-value
        map-options
        @update:model-value="(v) => filters.setStatus(v as Status[])"
      />
      <span class="visually-hidden" data-testid="filter-status-selected">{{ filters.fields.status.join(',') }}</span>
    </div>

    <div class="field">
      <q-select
        data-testid="filter-priority"
        label="Priority"
        :options="[...PRIORITIES]"
        :model-value="filters.fields.priority"
        multiple
        emit-value
        map-options
        @update:model-value="(v) => filters.setPriority(v as Priority[])"
      />
      <span class="visually-hidden" data-testid="filter-priority-selected">{{ filters.fields.priority.join(',') }}</span>
    </div>

    <div class="field">
      <q-select
        data-testid="filter-assignee"
        label="Assignee"
        :options="assigneeOptions()"
        :model-value="filters.fields.assignee ?? ANY_ASSIGNEE"
        emit-value
        map-options
        @update:model-value="onAssigneeChange"
      />
    </div>

    <fieldset class="field created-range">
      <legend>Created between</legend>
      <q-input
        data-testid="filter-created-from"
        type="date"
        label="From"
        :model-value="filters.fields.createdFrom ?? ''"
        @update:model-value="onFromChange"
      />
      <q-input
        data-testid="filter-created-to"
        type="date"
        label="To"
        :model-value="filters.fields.createdTo ?? ''"
        @update:model-value="onToChange"
      />
    </fieldset>

    <div class="field clear-field">
      <span data-testid="filter-active-count">{{ filters.activeCount }} active</span>
      <q-btn
        label="Clear filters"
        data-testid="filter-clear-button"
        :disable="filters.activeCount.value === 0"
        @click="filters.clear"
      />
    </div>
  </form>
</template>
