// builds/react-antd/src/toasts/ToastRegion.tsx
import type { KeyboardEvent } from 'react';
import { useToasts } from './ToastContext.js';

/**
 * The live region exists in the DOM from first render, before any toast fires,
 * so `aria-live="polite"` announcements are not missed on the first push.
 */
export function ToastRegion() {
  const { toasts, dismiss } = useToasts();

  const onKeyDown = (id: number) => (event: KeyboardEvent<HTMLDivElement>) => {
    if (event.key === 'Escape') {
      event.stopPropagation();
      dismiss(id);
    }
  };

  return (
    <div className="toast-region" aria-live="polite" aria-atomic="false">
      {toasts.map((toast) => (
        <div key={toast.id} className="toast" role="status" tabIndex={0} onKeyDown={onKeyDown(toast.id)}>
          <span>{toast.message}</span>
          <button type="button" aria-label="Dismiss notification" onClick={() => dismiss(toast.id)}>
            &times;
          </button>
        </div>
      ))}
    </div>
  );
}

// builds/vue-quasar/src/components/ToastRegion.vue
<script setup lang="ts">
import { useToasts } from '../toasts.js';

/**
 * The live region exists in the DOM from first render, before any toast fires,
 * so `aria-live="polite"` announcements are not missed on the first push.
 */
const toasts = useToasts();

function onKeydown(id: number, event: KeyboardEvent) {
  if (event.key === 'Escape') {
    event.stopPropagation();
    toasts.dismiss(id);
  }
}
</script>

<template>
  <div class="toast-region" aria-live="polite" aria-atomic="false">
    <div
      v-for="toast in toasts.toasts"
      :key="toast.id"
      class="toast"
      role="status"
      tabindex="0"
      @keydown="onKeydown(toast.id, $event)"
    >
      <span>{{ toast.message }}</span>
      <q-btn dense flat round aria-label="Dismiss notification" label="×" @click="toasts.dismiss(toast.id)" />
    </div>
  </div>
</template>
