// builds/vue-quasar/src/components/FilterForm.vue
<script setup lang="ts">
import { PRIORITIES, STATUSES, type Priority, type Status } from '@bakeoff/fixture';
import type { FiltersApi } from '../useFilters.js';

/** Section 5. Filters on every keystroke or change, no submit button. */
const props = defineProps<{ filters: FiltersApi; assignees: readonly string[] }>();

const ANY_ASSIGNEE = 'Any assignee';

const assigneeOptions = () => [ANY_ASSIGNEE, ...props.assignees, 'Unassigned'];

function onFromChange(value: string | number | null) {
  const text = value === null ? '' : String(value);
  props.filters.setCreatedFrom(text === '' ? null : text);
}

function onToChange(value: string | number | null) {
  const text = value === null ? '' : String(value);
  props.filters.setCreatedTo(text === '' ? null : text);
}

function onAssigneeChange(value: string) {
  props.filters.setAssignee(value === ANY_ASSIGNEE ? null : value);
}
</script>

<template>
  <form class="filter-form" aria-label="Filter tickets" @submit.prevent>
    <div class="field">
      <q-input
        data-testid="filter-search"
        label="Search"
        placeholder="Search id or subject"
        :model-value="filters.fields.search"
        @update:model-value="(v) => filters.setSearch(String(v ?? ''))"
      />
    </div>

    <div class="field">
      <q-select
        data-testid="filter-status"
        label="Status"
        :options="[...STATUSES]"
        :model-value="filters.fields.status"
        multiple
        emit-value
        map-options
        @update:model-value="(v) => filters.setStatus(v as Status[])"
      />
      <span class="visually-hidden" data-testid="filter-status-selected">{{ filters.fields.status.join(',') }}</span>
    </div>

    <div class="field">
      <q-select
        data-testid="filter-priority"
        label="Priority"
        :options="[...PRIORITIES]"
        :model-value="filters.fields.priority"
        multiple
        emit-value
        map-options
        @update:model-value="(v) => filters.setPriority(v as Priority[])"
      />
      <span class="visually-hidden" data-testid="filter-priority-selected">{{ filters.fields.priority.join(',') }}</span>
    </div>

    <div class="field">
      <q-select
        data-testid="filter-assignee"
        label="Assignee"
        :options="assigneeOptions()"
        :model-value="filters.fields.assignee ?? ANY_ASSIGNEE"
        emit-value
        map-options
        @update:model-value="onAssigneeChange"
      />
    </div>

    <fieldset class="field created-range">
      <legend>Created between</legend>
      <q-input
        data-testid="filter-created-from"
        type="date"
        label="From"
        :model-value="filters.fields.createdFrom ?? ''"
        @update:model-value="onFromChange"
      />
      <q-input
        data-testid="filter-created-to"
        type="date"
        label="To"
        :model-value="filters.fields.createdTo ?? ''"
        @update:model-value="onToChange"
      />
    </fieldset>

    <div class="field clear-field">
      <span data-testid="filter-active-count">{{ filters.activeCount }} active</span>
      <q-btn
        label="Clear filters"
        data-testid="filter-clear-button"
        :disable="filters.activeCount.value === 0"
        @click="filters.clear"
      />
    </div>
  </form>
</template>

// builds/react-headless/src/components/FilterForm.tsx
import type { ChangeEvent } from 'react';
import { PRIORITIES, STATUSES, type Priority, type Status } from '@bakeoff/fixture';
import type { FiltersApi } from '../useFilters.js';
import { MultiSelectField } from './MultiSelectField.js';
import { SingleSelectField } from './SingleSelectField.js';

/** Section 5. Filters on every keystroke or change, no submit button. */
export function FilterForm({ filters, assignees }: { filters: FiltersApi; assignees: readonly string[] }) {
  const onSearchChange = (event: ChangeEvent<HTMLInputElement>) => filters.setSearch(event.target.value);
  const onFromChange = (event: ChangeEvent<HTMLInputElement>) =>
    filters.setCreatedFrom(event.target.value === '' ? null : event.target.value);
  const onToChange = (event: ChangeEvent<HTMLInputElement>) =>
    filters.setCreatedTo(event.target.value === '' ? null : event.target.value);

  return (
    <form className="filter-form" aria-label="Filter tickets" onSubmit={(e) => e.preventDefault()}>
      <div className="field">
        <label htmlFor="search-input">Search</label>
        <input
          id="search-input"
          type="text"
          value={filters.fields.search}
          onChange={onSearchChange}
          placeholder="Search id or subject"
        />
      </div>

      <MultiSelectField<Status>
        testId="filter-status"
        label="Status"
        options={STATUSES}
        value={filters.fields.status}
        onChange={filters.setStatus}
      />

      <MultiSelectField<Priority>
        testId="filter-priority"
        label="Priority"
        options={PRIORITIES}
        value={filters.fields.priority}
        onChange={filters.setPriority}
      />

      <SingleSelectField<string>
        testId="filter-assignee"
        label="Assignee"
        options={[...assignees, 'Unassigned']}
        value={filters.fields.assignee}
        onChange={filters.setAssignee}
        nullOption="Any assignee"
      />

      <fieldset className="field created-range">
        <legend>Created between</legend>
        <label htmlFor="created-from">
          From
          <input id="created-from" type="date" value={filters.fields.createdFrom ?? ''} onChange={onFromChange} />
        </label>
        <label htmlFor="created-to">
          To
          <input id="created-to" type="date" value={filters.fields.createdTo ?? ''} onChange={onToChange} />
        </label>
      </fieldset>

      <div className="field clear-field">
        <span data-testid="filter-active-count">{filters.activeCount} active</span>
        <button
          type="button"
          data-testid="filter-clear-button"
          onClick={filters.clear}
          disabled={filters.activeCount === 0}
        >
          Clear filters
        </button>
      </div>
    </form>
  );
}
