// builds/react-headless/src/components/TicketsTable.tsx
import type { KeyboardEvent } from 'react';
import { PAGE_SIZE, type Ticket } from '@bakeoff/fixture';
import { formatDate, formatRelative } from '../format.js';
import type { SortColumn, SortDirection } from '../filtering.js';
import { sortRows } from '../filtering.js';
import { Badge } from './Badge.js';

export interface SortState {
  column: SortColumn | null;
  direction: SortDirection;
}

const COLUMNS: { key: SortColumn; label: string }[] = [
  { key: 'id', label: 'ID' },
  { key: 'subject', label: 'Subject' },
  { key: 'created', label: 'Created' },
  { key: 'updated', label: 'Updated' },
];

function ariaSortFor(sort: SortState, column: SortColumn): 'ascending' | 'descending' | undefined {
  if (sort.column !== column) return undefined;
  return sort.direction;
}

export function TicketsTable({
  filtered,
  page,
  onPageChange,
  sort,
  onSort,
  onOpenRow,
  emptyKind,
  emptyMessage,
  onClearFilters,
}: {
  filtered: Ticket[];
  page: number;
  onPageChange: (page: number) => void;
  sort: SortState;
  onSort: (column: SortColumn) => void;
  onOpenRow: (ticket: Ticket) => void;
  emptyKind: 'no-tickets' | 'no-matches' | null;
  emptyMessage: string | null;
  onClearFilters: () => void;
}) {
  const total = filtered.length;
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  const clampedPage = Math.min(Math.max(page, 1), totalPages);
  const sorted = sortRows(filtered, sort.column, sort.direction);
  const pageRows = sorted.slice((clampedPage - 1) * PAGE_SIZE, clampedPage * PAGE_SIZE);
  const start = total === 0 ? 0 : (clampedPage - 1) * PAGE_SIZE + 1;
  const end = Math.min(clampedPage * PAGE_SIZE, total);

  const onRowKeyDown = (ticket: Ticket) => (event: KeyboardEvent<HTMLTableRowElement>) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      onOpenRow(ticket);
    }
  };

  return (
    <div className="table-region">
      <table>
        <caption className="visually-hidden">Support tickets</caption>
        <thead>
          <tr>
            {COLUMNS.slice(0, 2).map((col) => (
              <th key={col.key} scope="col" aria-sort={ariaSortFor(sort, col.key) ?? 'none'}>
                <button type="button" onClick={() => onSort(col.key)}>
                  {col.label}
                  {sort.column === col.key ? (sort.direction === 'ascending' ? ' ▲' : ' ▼') : ''}
                </button>
              </th>
            ))}
            <th scope="col">Status</th>
            <th scope="col">Priority</th>
            <th scope="col">Assignee</th>
            {COLUMNS.slice(2).map((col) => (
              <th key={col.key} scope="col" aria-sort={ariaSortFor(sort, col.key) ?? 'none'}>
                <button type="button" onClick={() => onSort(col.key)}>
                  {col.label}
                  {sort.column === col.key ? (sort.direction === 'ascending' ? ' ▲' : ' ▼') : ''}
                </button>
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {emptyKind ? (
            <tr>
              <td colSpan={7} data-testid="table-empty-state" data-kind={emptyKind}>
                <p>{emptyMessage}</p>
                {emptyKind === 'no-matches' ? (
                  <button type="button" onClick={onClearFilters}>
                    Clear filters
                  </button>
                ) : null}
              </td>
            </tr>
          ) : (
            pageRows.map((ticket) => (
              <tr
                key={ticket.id}
                data-testid="ticket-row"
                tabIndex={0}
                onClick={() => onOpenRow(ticket)}
                onKeyDown={onRowKeyDown(ticket)}
              >
                <td>{ticket.id}</td>
                <td>{ticket.subject}</td>
                <td>
                  <Badge kind="status" value={ticket.status} />
                </td>
                <td>
                  <Badge kind="priority" value={ticket.priority} />
                </td>
                <td>{ticket.assignee ?? 'Unassigned'}</td>
                <td>{formatDate(ticket.createdAt)}</td>
                <td>{formatRelative(ticket.updatedAt)}</td>
              </tr>
            ))
          )}
        </tbody>
      </table>

      {emptyKind ? null : (
        <div className="pagination">
          <p aria-live="polite">
            Showing {start} to {end} of {total}
          </p>
          <button type="button" onClick={() => onPageChange(1)} disabled={clampedPage === 1}>
            First
          </button>
          <button type="button" onClick={() => onPageChange(clampedPage - 1)} disabled={clampedPage === 1}>
            Previous
          </button>
          <button type="button" onClick={() => onPageChange(clampedPage + 1)} disabled={clampedPage === totalPages}>
            Next
          </button>
          <button type="button" onClick={() => onPageChange(totalPages)} disabled={clampedPage === totalPages}>
            Last
          </button>
        </div>
      )}
    </div>
  );
}

// builds/vue-primevue/src/components/TicketsTable.vue
<script setup lang="ts">
import { computed } from 'vue';
import Button from 'primevue/button';
import Column from 'primevue/column';
import DataTable from 'primevue/datatable';
import { PAGE_SIZE, type Ticket } from '@bakeoff/fixture';
import { formatDate, formatRelative } from '../format.js';
import { sortRows } from '../filtering.js';
import type { EmptyKind } from '@bakeoff/harness';
import Badge from './Badge.vue';

/**
 * Section 4's table. PrimeVue's `DataTable` supplies the real `table` markup,
 * the sortable-column click/keyboard handling and `aria-sort`, the row focus and
 * Enter/Space-to-open behaviour (via `selectionMode="single"`), and the
 * paginator's First/Previous/Next/Last controls and `Showing x to y of z`
 * report. Nothing here reimplements any of that.
 *
 * `selection` is deliberately left unbound: PrimeVue's row click toggles
 * selection off on a second click of the same row, which would silently stop
 * the row from reopening the modal. Leaving `selection` at its default `null`
 * means every click, Enter, or Space always takes the same "select" branch,
 * which always emits `row-click`, the event this component actually listens
 * for.
 */
const props = defineProps<{
  filtered: Ticket[];
  sortField: string | null;
  sortOrder: number | null;
  first: number;
  emptyKind: EmptyKind;
  emptyMessage: string | null;
}>();

const emit = defineEmits<{
  'update:sortField': [value: string | null];
  'update:sortOrder': [value: number | null];
  'update:first': [value: number];
  'open-row': [ticket: Ticket];
  'clear-filters': [];
}>();

// The default order from section 4: `updatedAt` descending. When `sortField`
// cycles back to null (the third click of the ascending/descending/default
// sequence), DataTable stops resorting its `value` and this is what shows.
const baseRows = computed(() => sortRows(props.filtered, null, 'descending'));

function onRowClick(event: { data: Ticket }): void {
  emit('open-row', event.data);
}
</script>

<template>
  <div class="table-region">
    <DataTable
      :value="baseRows"
      data-key="id"
      selection-mode="single"
      :selection="null"
      :sort-field="sortField"
      :sort-order="sortOrder"
      sort-mode="single"
      removable-sort
      paginator
      :rows="PAGE_SIZE"
      :first="first"
      current-page-report-template="Showing {first} to {last} of {totalRecords}"
      paginator-template="FirstPageLink PrevPageLink CurrentPageReport NextPageLink LastPageLink"
      :table-props="{ 'aria-label': 'Support tickets' }"
      :pt="{ pcPaginator: { current: { 'aria-live': 'polite' } } }"
      @update:sort-field="(v) => emit('update:sortField', v)"
      @update:sort-order="(v) => emit('update:sortOrder', v)"
      @update:first="(v) => emit('update:first', v)"
      @row-click="onRowClick"
    >
      <template #empty>
        <div data-testid="table-empty-state" :data-kind="emptyKind">
          <p>{{ emptyMessage }}</p>
          <Button v-if="emptyKind === 'no-matches'" type="button" label="Clear filters" @click="emit('clear-filters')" />
        </div>
      </template>

      <Column field="id" header="ID" sortable />
      <Column field="subject" header="Subject" sortable />
      <Column header="Status">
        <template #body="{ data }"><Badge kind="status" :value="data.status" /></template>
      </Column>
      <Column header="Priority">
        <template #body="{ data }"><Badge kind="priority" :value="data.priority" /></template>
      </Column>
      <Column header="Assignee">
        <template #body="{ data }">{{ data.assignee ?? 'Unassigned' }}</template>
      </Column>
      <Column field="createdAt" header="Created" sortable>
        <template #body="{ data }">{{ formatDate(data.createdAt) }}</template>
      </Column>
      <Column field="updatedAt" header="Updated" sortable>
        <template #body="{ data }">{{ formatRelative(data.updatedAt) }}</template>
      </Column>
    </DataTable>
  </div>
</template>
