// builds/react-mui/src/toasts/ToastRegion.tsx
import type { KeyboardEvent } from 'react';
import { Alert } from '@mui/material';
import { useToasts } from './ToastContext.js';

/**
 * The live region exists in the DOM from first render, before any toast fires,
 * so `aria-live="polite"` announcements are not missed on the first push.
 * Each entry is an MUI `Alert`, which gives the close button (with its own
 * `aria-label`) for free; the Escape-to-dismiss handler is hand built.
 */
export function ToastRegion() {
  const { toasts, dismiss } = useToasts();

  const onKeyDown = (id: number) => (event: KeyboardEvent<HTMLDivElement>) => {
    if (event.key === 'Escape') {
      event.stopPropagation();
      dismiss(id);
    }
  };

  return (
    <div className="toast-region" aria-live="polite" aria-atomic="false" data-testid="toast-region">
      {toasts.map((toast) => (
        <Alert
          key={toast.id}
          severity="success"
          variant="filled"
          className="toast"
          data-testid="toast"
          tabIndex={0}
          onKeyDown={onKeyDown(toast.id)}
          onClose={() => dismiss(toast.id)}
        >
          {toast.message}
        </Alert>
      ))}
    </div>
  );
}

// builds/vue-primevue/src/components/ToastRegion.vue
<script setup lang="ts">
import type { Toast } from '../composables/useToasts.js';

/**
 * The live region exists in the DOM from first render, before any toast fires,
 * so `aria-live="polite"` announcements are not missed on the first push.
 */
defineProps<{ toasts: Toast[] }>();
const emit = defineEmits<{ dismiss: [id: number] }>();

function onKeydown(id: number, event: KeyboardEvent): void {
  if (event.key === 'Escape') {
    event.stopPropagation();
    emit('dismiss', id);
  }
}
</script>

<template>
  <div class="toast-region" aria-live="polite" aria-atomic="false">
    <div
      v-for="toast in toasts"
      :key="toast.id"
      class="toast"
      role="status"
      tabindex="0"
      @keydown="(event) => onKeydown(toast.id, event)"
    >
      <span>{{ toast.message }}</span>
      <button type="button" aria-label="Dismiss notification" @click="emit('dismiss', toast.id)">&times;</button>
    </div>
  </div>
</template>
