// builds/vue-vuetify/src/components/TicketsTable.vue
<script setup lang="ts">
import { computed } from 'vue';
import { PAGE_SIZE, type Ticket } from '@bakeoff/fixture';
import { formatDate, formatRelative } from '../format.js';
import { sortRows, type SortColumn, type SortDirection } from '../filtering.js';
import Badge from './Badge.vue';

export interface SortState {
  column: SortColumn | null;
  direction: SortDirection;
}

const props = defineProps<{
  filtered: Ticket[];
  page: number;
  sort: SortState;
  emptyKind: 'no-tickets' | 'no-matches' | null;
  emptyMessage: string | null;
}>();

const emit = defineEmits<{
  'page-change': [page: number];
  sort: [column: SortColumn];
  'open-row': [ticket: Ticket];
  'clear-filters': [];
}>();

const COLUMNS: { key: SortColumn; label: string }[] = [
  { key: 'id', label: 'ID' },
  { key: 'subject', label: 'Subject' },
  { key: 'created', label: 'Created' },
  { key: 'updated', label: 'Updated' },
];

function ariaSortFor(column: SortColumn): 'ascending' | 'descending' | 'none' {
  if (props.sort.column !== column) return 'none';
  return props.sort.direction;
}

const totalPages = computed(() => Math.max(1, Math.ceil(props.filtered.length / PAGE_SIZE)));
const clampedPage = computed(() => Math.min(Math.max(props.page, 1), totalPages.value));
const sorted = computed(() => sortRows(props.filtered, props.sort.column, props.sort.direction));
const pageRows = computed(() =>
  sorted.value.slice((clampedPage.value - 1) * PAGE_SIZE, clampedPage.value * PAGE_SIZE),
);
const total = computed(() => props.filtered.length);
const start = computed(() => (total.value === 0 ? 0 : (clampedPage.value - 1) * PAGE_SIZE + 1));
const end = computed(() => Math.min(clampedPage.value * PAGE_SIZE, total.value));

function onRowKeydown(ticket: Ticket, event: KeyboardEvent): void {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    emit('open-row', ticket);
  }
}
</script>

<template>
  <div class="table-region">
    <v-table>
      <caption class="visually-hidden">Support tickets</caption>
      <thead>
        <tr>
          <th
            v-for="col in COLUMNS.slice(0, 2)"
            :key="col.key"
            scope="col"
            :aria-sort="ariaSortFor(col.key)"
          >
            <v-btn :data-testid="`sort-${col.key}`" variant="text" density="compact" @click="emit('sort', col.key)">
              {{ col.label }}<span aria-hidden="true">{{ sort.column === col.key ? (sort.direction === 'ascending' ? ' ▲' : ' ▼') : '' }}</span>
            </v-btn>
          </th>
          <th scope="col">Status</th>
          <th scope="col">Priority</th>
          <th scope="col">Assignee</th>
          <th
            v-for="col in COLUMNS.slice(2)"
            :key="col.key"
            scope="col"
            :aria-sort="ariaSortFor(col.key)"
          >
            <v-btn :data-testid="`sort-${col.key}`" variant="text" density="compact" @click="emit('sort', col.key)">
              {{ col.label }}<span aria-hidden="true">{{ sort.column === col.key ? (sort.direction === 'ascending' ? ' ▲' : ' ▼') : '' }}</span>
            </v-btn>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-if="emptyKind">
          <td colspan="7" data-testid="table-empty-state" :data-kind="emptyKind">
            <p>{{ emptyMessage }}</p>
            <v-btn
              v-if="emptyKind === 'no-matches'"
              data-testid="empty-state-action"
              variant="tonal"
              @click="emit('clear-filters')"
            >
              Clear filters
            </v-btn>
          </td>
        </tr>
        <tr
          v-for="ticket in pageRows"
          v-else
          :key="ticket.id"
          data-testid="ticket-row"
          tabindex="0"
          @click="emit('open-row', ticket)"
          @keydown="onRowKeydown(ticket, $event)"
        >
          <td>{{ ticket.id }}</td>
          <td>{{ ticket.subject }}</td>
          <td><Badge kind="status" :value="ticket.status" /></td>
          <td><Badge kind="priority" :value="ticket.priority" /></td>
          <td>{{ ticket.assignee ?? 'Unassigned' }}</td>
          <td>{{ formatDate(ticket.createdAt) }}</td>
          <td>{{ formatRelative(ticket.updatedAt) }}</td>
        </tr>
      </tbody>
    </v-table>

    <div v-if="!emptyKind" class="pagination">
      <p aria-live="polite">Showing {{ start }} to {{ end }} of {{ total }}</p>
      <v-btn data-testid="page-first" variant="tonal" density="compact" :disabled="clampedPage === 1" @click="emit('page-change', 1)">First</v-btn>
      <v-btn data-testid="page-previous" variant="tonal" density="compact" :disabled="clampedPage === 1" @click="emit('page-change', clampedPage - 1)">Previous</v-btn>
      <v-btn data-testid="page-next" variant="tonal" density="compact" :disabled="clampedPage === totalPages" @click="emit('page-change', clampedPage + 1)">Next</v-btn>
      <v-btn data-testid="page-last" variant="tonal" density="compact" :disabled="clampedPage === totalPages" @click="emit('page-change', totalPages)">Last</v-btn>
    </div>
  </div>
</template>

// builds/react-shadcn/src/components/TicketsTable.tsx
import type { KeyboardEvent, MouseEvent, MutableRefObject } from 'react';
import { PAGE_SIZE, type Ticket } from '@bakeoff/fixture';
import { formatDate, formatRelative } from '../format.js';
import type { SortColumn, SortDirection } from '../filtering.js';
import { sortRows } from '../filtering.js';
import { TicketBadge } from './TicketBadge.js';
import { Button } from '@/components/ui/button.js';
import { Table, TableBody, TableCaption, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table.js';

export interface SortState {
  column: SortColumn | null;
  direction: SortDirection;
}

const COLUMNS: { key: SortColumn; label: string }[] = [
  { key: 'id', label: 'ID' },
  { key: 'subject', label: 'Subject' },
  { key: 'created', label: 'Created' },
  { key: 'updated', label: 'Updated' },
];

function ariaSortFor(sort: SortState, column: SortColumn): 'ascending' | 'descending' | undefined {
  if (sort.column !== column) return undefined;
  return sort.direction;
}

/**
 * shadcn/ui's Table is styling only, so section 4's sort cycle, pagination,
 * and the row-as-a-button keyboard handling (Enter/Space open the modal) are
 * all hand built against real `table` markup.
 */
export function TicketsTable({
  filtered,
  page,
  onPageChange,
  sort,
  onSort,
  onOpenRow,
  returnFocusRef,
  emptyKind,
  emptyMessage,
  onClearFilters,
}: {
  filtered: Ticket[];
  page: number;
  onPageChange: (page: number) => void;
  sort: SortState;
  onSort: (column: SortColumn) => void;
  onOpenRow: (ticket: Ticket) => void;
  /** Set to the clicked/activated row before `onOpenRow` fires, so the modal can focus it back on close. */
  returnFocusRef: MutableRefObject<HTMLElement | null>;
  emptyKind: 'no-tickets' | 'no-matches' | null;
  emptyMessage: string | null;
  onClearFilters: () => void;
}) {
  const total = filtered.length;
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  const clampedPage = Math.min(Math.max(page, 1), totalPages);
  const sorted = sortRows(filtered, sort.column, sort.direction);
  const pageRows = sorted.slice((clampedPage - 1) * PAGE_SIZE, clampedPage * PAGE_SIZE);
  const start = total === 0 ? 0 : (clampedPage - 1) * PAGE_SIZE + 1;
  const end = Math.min(clampedPage * PAGE_SIZE, total);

  const openRow = (ticket: Ticket, row: HTMLElement) => {
    returnFocusRef.current = row;
    onOpenRow(ticket);
  };

  const onRowClick = (ticket: Ticket) => (event: MouseEvent<HTMLTableRowElement>) => {
    openRow(ticket, event.currentTarget);
  };

  const onRowKeyDown = (ticket: Ticket) => (event: KeyboardEvent<HTMLTableRowElement>) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      openRow(ticket, event.currentTarget);
    }
  };

  const sortHeader = (col: (typeof COLUMNS)[number]) => (
    <TableHead key={col.key} scope="col" aria-sort={ariaSortFor(sort, col.key) ?? 'none'}>
      <button
        type="button"
        className="inline-flex items-center gap-1 rounded font-medium hover:text-foreground focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-ring"
        onClick={() => onSort(col.key)}
      >
        {col.label}
        {sort.column === col.key ? (sort.direction === 'ascending' ? ' ▲' : ' ▼') : ''}
      </button>
    </TableHead>
  );

  return (
    <div className="table-region">
      <Table>
        <TableCaption className="visually-hidden">Support tickets</TableCaption>
        <TableHeader>
          <TableRow>
            {sortHeader(COLUMNS[0] as (typeof COLUMNS)[number])}
            {sortHeader(COLUMNS[1] as (typeof COLUMNS)[number])}
            <TableHead scope="col">Status</TableHead>
            <TableHead scope="col">Priority</TableHead>
            <TableHead scope="col">Assignee</TableHead>
            {sortHeader(COLUMNS[2] as (typeof COLUMNS)[number])}
            {sortHeader(COLUMNS[3] as (typeof COLUMNS)[number])}
          </TableRow>
        </TableHeader>
        <TableBody>
          {emptyKind ? (
            <TableRow>
              <TableCell colSpan={7} data-testid="table-empty-state" data-kind={emptyKind} className="py-8 text-center">
                <p className="mb-3">{emptyMessage}</p>
                {emptyKind === 'no-matches' ? (
                  <Button type="button" variant="outline" onClick={onClearFilters}>
                    Clear filters
                  </Button>
                ) : null}
              </TableCell>
            </TableRow>
          ) : (
            pageRows.map((ticket) => (
              <TableRow
                key={ticket.id}
                data-testid="ticket-row"
                tabIndex={0}
                className="cursor-pointer"
                onClick={onRowClick(ticket)}
                onKeyDown={onRowKeyDown(ticket)}
              >
                <TableCell>{ticket.id}</TableCell>
                <TableCell>{ticket.subject}</TableCell>
                <TableCell>
                  <TicketBadge value={ticket.status} />
                </TableCell>
                <TableCell>
                  <TicketBadge value={ticket.priority} />
                </TableCell>
                <TableCell>{ticket.assignee ?? 'Unassigned'}</TableCell>
                <TableCell>{formatDate(ticket.createdAt)}</TableCell>
                <TableCell>{formatRelative(ticket.updatedAt)}</TableCell>
              </TableRow>
            ))
          )}
        </TableBody>
      </Table>

      {emptyKind ? null : (
        <div className="mt-3 flex flex-wrap items-center gap-3">
          <p aria-live="polite" className="text-sm text-muted-foreground">
            Showing {start} to {end} of {total}
          </p>
          <div className="flex gap-1.5">
            <Button type="button" variant="outline" size="sm" onClick={() => onPageChange(1)} disabled={clampedPage === 1}>
              First
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => onPageChange(clampedPage - 1)}
              disabled={clampedPage === 1}
            >
              Previous
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => onPageChange(clampedPage + 1)}
              disabled={clampedPage === totalPages}
            >
              Next
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => onPageChange(totalPages)}
              disabled={clampedPage === totalPages}
            >
              Last
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
