// builds/vue-quasar/src/TicketsScreen.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { loadAssignees, type FixtureOptions, type Ticket } from '@uilc/fixture';
import { useTicketData } from './useTicketData.js';
import { useFilters } from './useFilters.js';
import { nextSort, type SortColumn, type SortDirection, type SortState } from './filtering.js';
import { provideToasts } from './toasts.js';
import ToastRegion from './components/ToastRegion.vue';
import FilterForm from './components/FilterForm.vue';
import TicketsTable from './components/TicketsTable.vue';
import RecordModal from './components/RecordModal.vue';
import LoadingSkeleton from './components/LoadingSkeleton.vue';
import ErrorState from './components/ErrorState.vue';

/**
 * The screen from sections 2 to 8: a filterable table, a filter form above it,
 * a record modal, and toasts. The toast region mounts unconditionally, before
 * the loading/error/ready branches below it, so `aria-live="polite"` is
 * already in the DOM before the first toast.
 */
const props = withDefaults(defineProps<{ fixture?: FixtureOptions }>(), { fixture: () => ({}) });

const toasts = provideToasts();
const { state: ticketState, retry } = useTicketData(props.fixture);

const rows = ref<Ticket[]>([]);
const assignees = ref<readonly string[]>([]);
const sort = ref<SortState>({ column: null, direction: 'ascending' });
const page = ref(1);
const editingTicket = ref<Ticket | null>(null);

watch(
  ticketState,
  (state) => {
    if (state.status === 'ready') rows.value = state.rows;
  },
  { immediate: true },
);

loadAssignees().then((names) => {
  assignees.value = names;
});

const filters = useFilters(
  () => rows.value,
  () => {
    page.value = 1;
  },
  () => toasts.push('Filters cleared', 3000),
);

function onSort(column: SortColumn) {
  const current = sort.value.column ? { column: sort.value.column, direction: sort.value.direction } : null;
  sort.value = nextSort(current, column) ?? { column: null, direction: 'ascending' as SortDirection };
}

function onSave(updated: Ticket) {
  rows.value = rows.value.map((t) => (t.id === updated.id ? updated : t));
}

const emptyKind = computed(() => {
  if (rows.value.length === 0) return 'no-tickets' as const;
  if (filters.filtered.value.length === 0) return 'no-matches' as const;
  return null;
});

const emptyMessage = computed(() => {
  if (emptyKind.value === 'no-tickets') return 'No tickets yet';
  if (emptyKind.value === 'no-matches') return 'No tickets match these filters';
  return null;
});
</script>

<template>
  <ToastRegion />

  <ErrorState v-if="ticketState.status === 'error'" :message="ticketState.message" @retry="retry" />
  <LoadingSkeleton v-else-if="ticketState.status === 'loading'" />
  <template v-else>
    <FilterForm :filters="filters" :assignees="assignees" />
    <TicketsTable
      :filtered="filters.filtered.value"
      :page="page"
      :sort="sort"
      :empty-kind="emptyKind"
      :empty-message="emptyMessage"
      @update:page="(p) => (page = p)"
      @sort="onSort"
      @open-row="(t) => (editingTicket = t)"
      @clear-filters="filters.clear"
    />
    <RecordModal :ticket="editingTicket" :assignees="assignees" @close="editingTicket = null" @save="onSave" />
  </template>
</template>

// builds/react-shadcn/src/TicketsScreen.tsx
import { useEffect, useRef, useState } from 'react';
import { loadAssignees, type FixtureOptions, type Ticket } from '@uilc/fixture';
import { useTicketData } from './useTicketData.js';
import { useFilters } from './useFilters.js';
import { nextSort, type SortColumn, type SortDirection } from './filtering.js';
import { ToastProvider, useToasts } from './toasts/ToastContext.js';
import { ToastRegion } from './toasts/ToastRegion.js';
import { FilterForm } from './components/FilterForm.js';
import { TicketsTable, type SortState } from './components/TicketsTable.js';
import { RecordModal } from './components/RecordModal.js';
import { LoadingSkeleton } from './components/LoadingSkeleton.js';
import { ErrorState } from './components/ErrorState.js';

/**
 * The screen from sections 2 to 8: a filterable table, the filter form above it,
 * a record modal, and toasts. The toast region mounts once, at the top, before
 * any of the loading, error, or ready states below it, so `aria-live="polite"`
 * is already in the DOM before the first toast.
 */
export function TicketsScreen({ fixture = {} }: { fixture?: FixtureOptions }) {
  return (
    <ToastProvider>
      <ToastRegion />
      <div className="mx-auto max-w-7xl p-6">
        <ScreenBody fixture={fixture} />
      </div>
    </ToastProvider>
  );
}

function ScreenBody({ fixture }: { fixture: FixtureOptions }) {
  const { state: ticketState, retry } = useTicketData(fixture);
  const [rows, setRows] = useState<Ticket[]>([]);
  const [assignees, setAssignees] = useState<readonly string[]>([]);
  const [sort, setSort] = useState<SortState>({ column: null, direction: 'ascending' });
  const [page, setPage] = useState(1);
  const [editingTicket, setEditingTicket] = useState<Ticket | null>(null);
  const returnFocusRef = useRef<HTMLElement | null>(null);
  const toasts = useToasts();

  useEffect(() => {
    if (ticketState.status === 'ready') setRows(ticketState.rows);
  }, [ticketState]);

  useEffect(() => {
    loadAssignees().then(setAssignees);
  }, []);

  const filters = useFilters(
    rows,
    () => setPage(1),
    () => toasts.push('Filters cleared', 3000),
  );

  const onSort = (column: SortColumn) => {
    setSort((prev) => {
      const current = prev.column ? { column: prev.column, direction: prev.direction } : null;
      return nextSort(current, column) ?? { column: null, direction: 'ascending' as SortDirection };
    });
  };

  const onSave = (updated: Ticket) => {
    setRows((prev) => prev.map((t) => (t.id === updated.id ? updated : t)));
  };

  if (ticketState.status === 'error') {
    return <ErrorState message={ticketState.message} onRetry={retry} />;
  }

  if (ticketState.status === 'loading') {
    return <LoadingSkeleton />;
  }

  const emptyKind = rows.length === 0 ? 'no-tickets' : filters.filtered.length === 0 ? 'no-matches' : null;
  const emptyMessage =
    emptyKind === 'no-tickets' ? 'No tickets yet' : emptyKind === 'no-matches' ? 'No tickets match these filters' : null;

  return (
    <>
      <h1 className="mb-4 text-xl font-semibold">Support tickets</h1>
      <FilterForm filters={filters} assignees={assignees} />
      <TicketsTable
        filtered={filters.filtered}
        page={page}
        onPageChange={setPage}
        sort={sort}
        onSort={onSort}
        onOpenRow={setEditingTicket}
        returnFocusRef={returnFocusRef}
        emptyKind={emptyKind}
        emptyMessage={emptyMessage}
        onClearFilters={filters.clear}
      />
      <RecordModal
        ticket={editingTicket}
        assignees={assignees}
        returnFocusRef={returnFocusRef}
        onClose={() => setEditingTicket(null)}
        onSave={onSave}
      />
    </>
  );
}
